name: Deploy

on:
  push:
    branches:
      - master
jobs:
  deploy-heroku:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby 2.6
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.6

      - name: install dependencies
        run: |
          # Build dependencies
          gem install dpl

      - name: deploy to heroku
        run: dpl --provider=heroku --app=${{ secrets.HEROKU_APP_MASTER }} --api-key=${{ secrets.HEROKU_API_KEY }}
